# Generated by Django 4.2 on 2026-07-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='additional_phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Bangladesh', 'Bangladesh'), ('Australia', 'Australia'), ('United States', 'United States'), ('Canada', 'Canada'), ('India', 'India'), ('UAE', 'UAE'), ('Malaysia', 'Malaysia')], max_length=100, null=True),
        ),
    ]
