# Generated by Django 4.2 on 2026-08-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_additional_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_education_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
