# Generated by Django 4.2 on 2026-07-30 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('govt_id', models.ImageField(blank=True, null=True, upload_to='tutor_govt_id/')),
                ('overview', models.TextField(blank=True, null=True)),
                ('tutoring_experience', models.CharField(blank=True, max_length=128, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('additional_phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='tutor_resume/')),
                ('class_count', models.IntegerField(default=0)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('reason_for_update', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tutor_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorEducation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('secondary_institute_name', models.CharField(blank=True, max_length=128, null=True)),
                ('secondary_degree', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_id', models.ImageField(blank=True, null=True, upload_to='tutor_secondary_id/')),
                ('secondary_result', models.CharField(blank=True, max_length=128, null=True)),
                ('secondary_certificate', models.FileField(blank=True, null=True, upload_to='tutor_secondary_certificate/')),
                ('secondary_passing_year', models.DateField(blank=True, null=True)),
                ('secondary_curriculum', models.CharField(blank=True, max_length=50, null=True)),
                ('currently_at_secondary', models.BooleanField(blank=True, default=False, null=True)),
                ('higher_secondary_institute_name', models.CharField(blank=True, max_length=128, null=True)),
                ('higher_secondary_degree', models.CharField(blank=True, max_length=50, null=True)),
                ('higher_secondary_id', models.ImageField(blank=True, null=True, upload_to='tutor_higher_secondary_id/')),
                ('higher_secondary_result', models.CharField(blank=True, max_length=128, null=True)),
                ('higher_secondary_certificate', models.FileField(blank=True, null=True, upload_to='tutor_higher_secondary_certificate/')),
                ('higher_secondary_passing_year', models.DateField(blank=True, null=True)),
                ('higher_secondary_curriculum', models.CharField(blank=True, max_length=50, null=True)),
                ('currently_at_higher_secondary', models.BooleanField(blank=True, default=False, null=True)),
                ('bachelors_institute_name', models.CharField(blank=True, max_length=128, null=True)),
                ('bachelors_id', models.ImageField(blank=True, null=True, upload_to='tutor_bachelors_id/')),
                ('bachelors_result', models.CharField(blank=True, max_length=128, null=True)),
                ('bachelors_certificate', models.FileField(blank=True, null=True, upload_to='tutor_bachelors_certificate/')),
                ('bachelors_passing_year', models.DateField(blank=True, null=True)),
                ('currently_at_bachelors', models.BooleanField(blank=True, default=False, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('reason_for_update', models.TextField(blank=True, null=True)),
                ('tutor_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_education_profile', to='user_profile.tutorprofile')),
            ],
            options={
                'db_table': 'tutor_education',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('institute', models.CharField(blank=True, max_length=128, null=True)),
                ('institute_id', models.ImageField(blank=True, null=True, upload_to='student_institute_id/')),
                ('curriculum', models.CharField(blank=True, max_length=128, null=True)),
                ('curriculum_level', models.CharField(blank=True, max_length=128, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relation_with_guardian', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_number', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('reason_for_update', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
